spring.application.name=pos-system
server.servlet.context-path=/api
server.port=8082
management.endpoints.web.exposure.include=health,caches
management.endpoint.caches.enabled=true
spring.cache.type=hazelcast

# Database connection
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/posdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rootpass}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# jpa
spring.jpa.open-in-view=false
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:create}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# OpenTelemetry configuration
otel.service.name=pos-system

# OpenTelemetry Configuration
otlp.endpoint=${OTEL_ENDPOINT}

application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

# hazelcast k8s API mode
hazelcast.k8s.namespace=${HAZELCAST_NAMESPACE:default}
hazelcast.k8s.service-name=${HAZELCAST_SERVICE_NAME:pos-backend}