apiVersion: v1
kind: ConfigMap
metadata:
  name: pos-config
  namespace: pos

data:
  # Spring Boot Database connection
  SPRING_DATASOURCE_URL: jdbc:mysql://pos-db-service:3306/posdb
  SPRING_JPA_HIBERNATE_DDL_AUTO: create
  SPRING_JPA_SHOW_SQL: "false"

  NEXT_PUBLIC_API_BASE_URL: /api