apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-backend
  namespace: pos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pos-backend
  template:
    metadata:
      labels:
        app: pos-backend
    spec:
      containers:
        - name: pos-backend
          image: docker.io/rprakashdass/pos-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: pos-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pos-secret
                  key: pos_db_username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pos-secret
                  key: pos_db_password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: pos-config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO
            - name: SPRING_JPA_SHOW_SQL
              valueFrom:
                configMapKeyRef:
                  name: pos-config
                  key: SPRING_JPA_SHOW_SQL
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8082
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /api/health
              port: 8082
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          startupProbe:
            httpGet:
              path: /api/health
              port: 8082
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 45