apiVersion: v1
kind: Service
metadata:
  name: pos-frontend-service
  namespace: pos
spec:
  selector:
    app: pos-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP