apiVersion: v1
kind: Service
metadata:
  name: pos-db-service
  namespace: pos
spec:
  clusterIP: None  # Headless service for stateful sets
  selector:
    app: pos-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306