apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pos-db
  namespace: pos
  labels:
    app: pos-db
spec:
  serviceName: "pos-db"
  replicas: 1
  selector:
    matchLabels:
      app: pos-db
  template:
    metadata:
      labels:
        app: pos-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pos-secret
                  key: pos_db_password
            - name: MYSQL_DATABASE
              value: posdb
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          limits:
            storage: 1Gi
          requests:
            storage: 500Mi